# Generated by Django 6.0.3 on 2026-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_restaurant_razorpay_account_id_restaurant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
