# Generated by Django 6.0.3 on 2026-05-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_deliverypartner_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='latitude',
            field=models.FloatField(default=12.9716),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='longitude',
            field=models.FloatField(default=77.5946),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_share',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_share',
            field=models.FloatField(default=0),
        ),
    ]
