# Generated by Django 6.0.3 on 2026-05-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_deliverypartner_latitude_deliverypartner_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
