services:
  - type: web
    name: luxebite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn meal_buddy.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SETTINGS_MODULE
        value: meal_buddy.settings
